#pragma once

#include <cstdint>

namespace openwow::game {

enum class SpellCastResult : std::uint8_t {
  // Vanilla 1.12.1 wire values.  Local-only success is deliberately outside
  // this server result range; Vanilla uses 0 for SPELL_FAILED_AFFECTING_COMBAT.
  kAffectingCombat = 0,
  kAlreadyAtFullHealth = 1,
  kAlreadyAtFullPower = 2,
  kAlreadyBeingTamed = 3,
  kAlreadyHaveCharm = 4,
  kAlreadyHaveSummon = 5,
  kAlreadyOpen = 6,
  kAuraBounced = 7,
  kAutotrackInterrupted = 8,
  kBadImplicitTargets = 9,
  kBadTargets = 10,
  kCantBeCharmed = 11,
  kCantBeDisenchanted = 12,
  kCantBeProspected = 13,
  kCantCastOnTapped = 14,
  kCantDuelWhileInvisible = 15,
  kCantDuelWhileStealthed = 16,
  kCantStealth = 17,
  kCasterAuraState = 18,
  kCasterDead = 19,
  kCharmed = 20,
  kChestInUse = 21,
  kConfused = 22,
  kDontReport = 23,
  kEquippedItem = 24,
  kEquippedItemClass = 25,
  kEquippedItemClassMainhand = 26,
  kEquippedItemClassOffhand = 27,
  kError = 28,
  kFizzle = 29,
  kFleeing = 30,
  kFoodLowLevel = 31,
  kHighLevel = 32,
  kHungerSatiated = 33,
  kImmune = 34,
  kInterrupted = 35,
  kInterruptedCombat = 36,
  kItemAlreadyEnchanted = 37,
  kItemGone = 38,
  kItemNotFound = 39,
  kItemNotReady = 40,
  kLevelRequirement = 41,
  kLineOfSight = 42,
  kLowLevel = 43,
  kLowCastLevel = 44,
  kMainhandEmpty = 45,
  kMoving = 46,
  kNeedAmmo = 47,
  kNeedAmmoPouch = 48,
  kNeedExoticAmmo = 49,
  kNoPath = 50,
  kNotBehind = 51,
  kNotFishable = 52,
  kNotHere = 53,
  kNotInfront = 54,
  kNotInControl = 55,
  kNotKnown = 56,
  kNotMounted = 57,
  kNotOnTaxi = 58,
  kNotOnTransport = 59,
  kNotReady = 60,
  kNotShapeshift = 61,
  kNotStanding = 62,
  kNotTradeable = 63,
  kNotTrading = 64,
  kNotUnsheathed = 65,
  kNotWhileGhost = 66,
  kNoAmmo = 67,
  kNoChargesRemain = 68,
  kNoChampion = 69,
  kNoComboPoints = 70,
  kNoDueling = 71,
  kNoEndurance = 72,
  kNoFish = 73,
  kNoItemsWhileShapeshifted = 74,
  kNoMountsAllowed = 75,
  kNoPet = 76,
  kNoPower = 77,
  kNothingToDispel = 78,
  kNothingToSteal = 79,
  kOnlyAbovewater = 80,
  kOnlyDaytime = 81,
  kOnlyIndoors = 82,
  kOnlyMounted = 83,
  kOnlyNighttime = 84,
  kOnlyOutdoors = 85,
  kOnlyShapeshift = 86,
  kOnlyStealthed = 87,
  kOnlyUnderwater = 88,
  kOutOfRange = 89,
  kPacified = 90,
  kPossessed = 91,
  kReagents = 92,
  kRequiresArea = 93,
  kRequiresSpellFocus = 94,
  kRooted = 95,
  kSilenced = 96,
  kSpellInProgress = 97,
  kSpellLearned = 98,
  kSpellUnavailable = 99,
  kStunned = 100,
  kTargetsDead = 101,
  kTargetAffectingCombat = 102,
  kTargetAuraState = 103,
  kTargetDueling = 104,
  kTargetEnemy = 105,
  kTargetEnraged = 106,
  kTargetFriendly = 107,
  kTargetInCombat = 108,
  kTargetIsPlayer = 109,
  kTargetNotDead = 110,
  kTargetNotInParty = 111,
  kTargetNotLooted = 112,
  kTargetNotPlayer = 113,
  kTargetNoPockets = 114,
  kTargetNoWeapons = 115,
  kTargetUnskinnable = 116,
  kThirstSatiated = 117,
  kTooClose = 118,
  kTooManyOfItem = 119,
  kTotems = 120,
  kTrainingPoints = 121,
  kTryAgain = 122,
  kUnitNotBehind = 123,
  kUnitNotInfront = 124,
  kWrongPetFood = 125,
  kNotWhileFatigued = 126,
  kTargetNotInInstance = 127,
  kNotWhileTrading = 128,
  kTargetNotInRaid = 129,
  kDisenchantWhileLooting = 130,
  kProspectWhileLooting = 131,
  kProspectNeedMore = 132,
  kTargetFreeforall = 133,
  kNoEdibleCorpses = 134,
  kOnlyBattlegrounds = 135,
  kTargetNotGhost = 136,
  kTooManySkills = 137,
  kTransformUnusable = 138,
  kWrongWeather = 139,
  kDamageImmune = 140,
  kPreventedByMechanic = 141,
  kPlayTime = 142,
  kReputation = 143,
  kMinSkill = 144,
  kUnknown = 145,

  // Client-side-only validation value; it is not part of the Vanilla wire
  // result table and must never be decoded from SMSG_CAST_RESULT.
  kNeedMoreItems = 146,

  // Internal sentinel; never serialize this value as a server result.
  kSuccess = 0xFF,
};

static_assert(static_cast<std::uint8_t>(SpellCastResult::kInterrupted) == 0x23);
static_assert(static_cast<std::uint8_t>(SpellCastResult::kFoodLowLevel) == 0x1F);
static_assert(static_cast<std::uint8_t>(SpellCastResult::kOutOfRange) == 0x59);
static_assert(static_cast<std::uint8_t>(SpellCastResult::kSuccess) == 0xFF);

[[nodiscard]] const char* SpellCastResultToString(SpellCastResult result);

}
