#pragma once

#include "openwow/game/object_types.h"

#include <cstdint>

namespace openwow::game {

enum EObjectFields : std::uint16_t {
  OBJECT_FIELD_GUID    = 0x0000,
  OBJECT_FIELD_TYPE    = 0x0002,
  OBJECT_FIELD_ENTRY   = 0x0003,
  OBJECT_FIELD_SCALE_X = 0x0004,
  OBJECT_FIELD_PADDING = 0x0005,
  OBJECT_END           = 0x0006,
};

enum EItemFields : std::uint16_t {
  ITEM_FIELD_OWNER              = OBJECT_END + 0x0000,
  ITEM_FIELD_CONTAINED          = OBJECT_END + 0x0002,
  ITEM_FIELD_CREATOR            = OBJECT_END + 0x0004,
  ITEM_FIELD_GIFTCREATOR        = OBJECT_END + 0x0006,
  ITEM_FIELD_STACK_COUNT        = OBJECT_END + 0x0008,
  ITEM_FIELD_DURATION           = OBJECT_END + 0x0009,
  ITEM_FIELD_SPELL_CHARGES      = OBJECT_END + 0x000A,
  ITEM_FIELD_SPELL_CHARGES_01   = OBJECT_END + 0x000B,
  ITEM_FIELD_SPELL_CHARGES_02   = OBJECT_END + 0x000C,
  ITEM_FIELD_SPELL_CHARGES_03   = OBJECT_END + 0x000D,
  ITEM_FIELD_SPELL_CHARGES_04   = OBJECT_END + 0x000E,
  ITEM_FIELD_FLAGS              = OBJECT_END + 0x000F,
  ITEM_FIELD_ENCHANTMENT        = OBJECT_END + 0x0010,
  ITEM_FIELD_ENCHANTMENT_1_1    = ITEM_FIELD_ENCHANTMENT,
  ITEM_FIELD_PROPERTY_SEED      = OBJECT_END + 0x0025,
  ITEM_FIELD_RANDOM_PROPERTIES_ID = OBJECT_END + 0x0026,
  ITEM_FIELD_ITEM_TEXT_ID       = OBJECT_END + 0x0027,
  ITEM_FIELD_DURABILITY         = OBJECT_END + 0x0028,
  ITEM_FIELD_MAXDURABILITY      = OBJECT_END + 0x0029,
  ITEM_UNSUPPORTED_FIELD        = OBJECT_END + 0x002A,
  ITEM_FIELD_CREATE_PLAYED_TIME = ITEM_UNSUPPORTED_FIELD,
  ITEM_FIELD_PAD                = ITEM_UNSUPPORTED_FIELD,
  ITEM_END                      = ITEM_UNSUPPORTED_FIELD,
};

enum EContainerFields : std::uint16_t {
  CONTAINER_FIELD_NUM_SLOTS = ITEM_END + 0x0000,
  CONTAINER_ALIGN_PAD       = ITEM_END + 0x0001,
  CONTAINER_FIELD_SLOT_1    = ITEM_END + 0x0002,
  CONTAINER_END             = ITEM_END + 0x004A,
};

enum EUnitFields : std::uint16_t {
  UNIT_FIELD_CHARM                 = OBJECT_END + 0x0000,
  UNIT_FIELD_SUMMON                = OBJECT_END + 0x0002,
  UNIT_FIELD_CHARMEDBY             = OBJECT_END + 0x0004,
  UNIT_FIELD_CRITTER               = UNIT_FIELD_CHARMEDBY,
  UNIT_FIELD_SUMMONEDBY            = OBJECT_END + 0x0006,
  UNIT_FIELD_CREATEDBY             = OBJECT_END + 0x0008,
  UNIT_FIELD_TARGET                = OBJECT_END + 0x000A,
  UNIT_FIELD_PERSUADED             = OBJECT_END + 0x000C,
  UNIT_FIELD_CHANNEL_OBJECT        = OBJECT_END + 0x000E,
  UNIT_FIELD_HEALTH                = OBJECT_END + 0x0010,
  UNIT_FIELD_POWER1                = OBJECT_END + 0x0011,
  UNIT_FIELD_POWER2                = OBJECT_END + 0x0012,
  UNIT_FIELD_POWER3                = OBJECT_END + 0x0013,
  UNIT_FIELD_POWER4                = OBJECT_END + 0x0014,
  UNIT_FIELD_POWER5                = OBJECT_END + 0x0015,
  UNIT_FIELD_POWER6                = UNIT_FIELD_POWER5,
  UNIT_FIELD_POWER7                = UNIT_FIELD_POWER5,
  UNIT_FIELD_MAXHEALTH             = OBJECT_END + 0x0016,
  UNIT_FIELD_MAXPOWER1             = OBJECT_END + 0x0017,
  UNIT_FIELD_MAXPOWER2             = OBJECT_END + 0x0018,
  UNIT_FIELD_MAXPOWER3             = OBJECT_END + 0x0019,
  UNIT_FIELD_MAXPOWER4             = OBJECT_END + 0x001A,
  UNIT_FIELD_MAXPOWER5             = OBJECT_END + 0x001B,
  UNIT_FIELD_MAXPOWER6             = UNIT_FIELD_MAXPOWER5,
  UNIT_FIELD_MAXPOWER7             = UNIT_FIELD_MAXPOWER5,
  UNIT_FIELD_LEVEL                 = OBJECT_END + 0x001C,
  UNIT_FIELD_FACTIONTEMPLATE       = OBJECT_END + 0x001D,
  UNIT_FIELD_BYTES_0               = OBJECT_END + 0x001E,
  UNIT_VIRTUAL_ITEM_DISPLAY        = OBJECT_END + 0x001F,
  UNIT_VIRTUAL_ITEM_INFO           = OBJECT_END + 0x0022,
  UNIT_VIRTUAL_ITEM_SLOT_ID        = UNIT_VIRTUAL_ITEM_DISPLAY,
  UNIT_FIELD_FLAGS                 = OBJECT_END + 0x0028,
  UNIT_FIELD_FLAGS_2               = UNIT_FIELD_FLAGS,
  UNIT_FIELD_AURA                  = OBJECT_END + 0x0029,
  UNIT_FIELD_AURA_LAST             = OBJECT_END + 0x0058,
  UNIT_FIELD_AURAFLAGS             = OBJECT_END + 0x0059,
  UNIT_FIELD_AURAFLAGS_01          = OBJECT_END + 0x005A,
  UNIT_FIELD_AURAFLAGS_02          = OBJECT_END + 0x005B,
  UNIT_FIELD_AURAFLAGS_03          = OBJECT_END + 0x005C,
  UNIT_FIELD_AURAFLAGS_04          = OBJECT_END + 0x005D,
  UNIT_FIELD_AURAFLAGS_05          = OBJECT_END + 0x005E,
  UNIT_FIELD_AURALEVELS            = OBJECT_END + 0x005F,
  UNIT_FIELD_AURALEVELS_LAST       = OBJECT_END + 0x006A,
  UNIT_FIELD_AURAAPPLICATIONS      = OBJECT_END + 0x006B,
  UNIT_FIELD_AURAAPPLICATIONS_LAST = OBJECT_END + 0x0076,
  UNIT_FIELD_AURASTATE             = OBJECT_END + 0x0077,
  UNIT_FIELD_BASEATTACKTIME        = OBJECT_END + 0x0078,
  UNIT_FIELD_OFFHANDATTACKTIME     = OBJECT_END + 0x0079,
  UNIT_FIELD_RANGEDATTACKTIME      = OBJECT_END + 0x007A,
  UNIT_FIELD_BOUNDINGRADIUS        = OBJECT_END + 0x007B,
  UNIT_FIELD_COMBATREACH           = OBJECT_END + 0x007C,
  UNIT_FIELD_DISPLAYID             = OBJECT_END + 0x007D,
  UNIT_FIELD_NATIVEDISPLAYID       = OBJECT_END + 0x007E,
  UNIT_FIELD_MOUNTDISPLAYID        = OBJECT_END + 0x007F,
  UNIT_FIELD_MINDAMAGE             = OBJECT_END + 0x0080,
  UNIT_FIELD_MAXDAMAGE             = OBJECT_END + 0x0081,
  UNIT_FIELD_MINOFFHANDDAMAGE      = OBJECT_END + 0x0082,
  UNIT_FIELD_MAXOFFHANDDAMAGE      = OBJECT_END + 0x0083,
  UNIT_FIELD_BYTES_1               = OBJECT_END + 0x0084,
  UNIT_FIELD_PETNUMBER             = OBJECT_END + 0x0085,
  UNIT_FIELD_PET_NAME_TIMESTAMP    = OBJECT_END + 0x0086,
  UNIT_FIELD_PETEXPERIENCE         = OBJECT_END + 0x0087,
  UNIT_FIELD_PETNEXTLEVELEXP       = OBJECT_END + 0x0088,
  UNIT_DYNAMIC_FLAGS               = OBJECT_END + 0x0089,
  UNIT_CHANNEL_SPELL               = OBJECT_END + 0x008A,
  UNIT_MOD_CAST_SPEED              = OBJECT_END + 0x008B,
  UNIT_CREATED_BY_SPELL            = OBJECT_END + 0x008C,
  UNIT_NPC_FLAGS                   = OBJECT_END + 0x008D,
  UNIT_NPC_EMOTESTATE              = OBJECT_END + 0x008E,
  UNIT_TRAINING_POINTS             = OBJECT_END + 0x008F,
  UNIT_FIELD_STAT0                 = OBJECT_END + 0x0090,
  UNIT_FIELD_STAT1                 = OBJECT_END + 0x0091,
  UNIT_FIELD_STAT2                 = OBJECT_END + 0x0092,
  UNIT_FIELD_STAT3                 = OBJECT_END + 0x0093,
  UNIT_FIELD_STAT4                 = OBJECT_END + 0x0094,
  UNIT_FIELD_RESISTANCES           = OBJECT_END + 0x0095,
  UNIT_FIELD_BASE_MANA             = OBJECT_END + 0x009C,
  UNIT_FIELD_BASE_HEALTH           = OBJECT_END + 0x009D,
  UNIT_FIELD_BYTES_2               = OBJECT_END + 0x009E,
  UNIT_FIELD_ATTACK_POWER          = OBJECT_END + 0x009F,
  UNIT_FIELD_ATTACK_POWER_MODS     = OBJECT_END + 0x00A0,
  UNIT_FIELD_ATTACK_POWER_MULTIPLIER = OBJECT_END + 0x00A1,
  UNIT_FIELD_RANGED_ATTACK_POWER   = OBJECT_END + 0x00A2,
  UNIT_FIELD_RANGED_ATTACK_POWER_MODS = OBJECT_END + 0x00A3,
  UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER = OBJECT_END + 0x00A4,
  UNIT_FIELD_MINRANGEDDAMAGE       = OBJECT_END + 0x00A5,
  UNIT_FIELD_MAXRANGEDDAMAGE       = OBJECT_END + 0x00A6,
  UNIT_FIELD_POWER_COST_MODIFIER   = OBJECT_END + 0x00A7,
  UNIT_FIELD_POWER_COST_MULTIPLIER = OBJECT_END + 0x00AE,
  UNIT_FIELD_PADDING               = OBJECT_END + 0x00B5,
  UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE = UNIT_FIELD_PADDING,
  UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE = UNIT_FIELD_PADDING,
  UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER = UNIT_FIELD_PADDING,
  UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER = UNIT_FIELD_PADDING,
  UNIT_FIELD_MAXHEALTHMODIFIER     = UNIT_FIELD_PADDING,
  UNIT_FIELD_HOVERHEIGHT           = UNIT_FIELD_PADDING,
  UNIT_FIELD_PADDING_END           = UNIT_FIELD_PADDING,
  // Classic UNIT_END is 0xBC (188 fields including OBJECT_END).
  UNIT_END                         = OBJECT_END + 0x00B6,
};

enum EPlayerFields : std::uint16_t {
  PLAYER_DUEL_ARBITER                  = UNIT_END + 0x0000,
  PLAYER_DUEL_ARBITER_END              = UNIT_END + 0x0002,
  PLAYER_FLAGS                         = UNIT_END + 0x0002,
  PLAYER_GUILDID                       = UNIT_END + 0x0003,
  PLAYER_GUILDRANK                     = UNIT_END + 0x0004,
  PLAYER_BYTES                         = UNIT_END + 0x0005,
  PLAYER_BYTES_2                       = UNIT_END + 0x0006,
  PLAYER_BYTES_3                       = UNIT_END + 0x0007,
  PLAYER_DUEL_TEAM                     = UNIT_END + 0x0008,
  PLAYER_GUILD_TIMESTAMP               = UNIT_END + 0x0009,

  PLAYER_QUEST_LOG_1_1                 = UNIT_END + 0x000A,
  PLAYER_QUEST_LOG_1_2                 = UNIT_END + 0x000B,
  PLAYER_QUEST_LOG_1_3                 = UNIT_END + 0x000C,
  PLAYER_QUEST_LOG_LAST_1              = UNIT_END + 0x0043,
  PLAYER_QUEST_LOG_LAST_2              = UNIT_END + 0x0044,
  PLAYER_QUEST_LOG_LAST_3              = UNIT_END + 0x0045,

  PLAYER_VISIBLE_ITEM_1_CREATOR        = UNIT_END + 0x0046,
  PLAYER_VISIBLE_ITEM_1_0              = UNIT_END + 0x0048,
  PLAYER_VISIBLE_ITEM_1_ENTRYID        = PLAYER_VISIBLE_ITEM_1_0,
  PLAYER_VISIBLE_ITEM_1_PROPERTIES     = UNIT_END + 0x0050,
  PLAYER_VISIBLE_ITEM_1_PAD            = UNIT_END + 0x0051,
  PLAYER_VISIBLE_ITEM_LAST_CREATOR     = UNIT_END + 0x011E,
  PLAYER_VISIBLE_ITEM_LAST_0           = UNIT_END + 0x0120,
  PLAYER_VISIBLE_ITEM_LAST_0_END       = UNIT_END + 0x0127,
  PLAYER_VISIBLE_ITEM_LAST_PROPERTIES  = UNIT_END + 0x0128,
  PLAYER_VISIBLE_ITEM_LAST_PAD         = UNIT_END + 0x0129,

  PLAYER_FIELD_INV_SLOT_HEAD           = UNIT_END + 0x012A,
  PLAYER_FIELD_INV_SLOT_END            = UNIT_END + 0x0157,
  PLAYER_FIELD_PACK_SLOT_1             = UNIT_END + 0x0158,
  PLAYER_FIELD_PACK_SLOT_LAST          = UNIT_END + 0x0176,
  PLAYER_FIELD_PACK_SLOT_END           = UNIT_END + 0x0177,
  PLAYER_FIELD_BANK_SLOT_1             = UNIT_END + 0x0178,
  PLAYER_FIELD_BANK_SLOT_LAST          = UNIT_END + 0x01A6,
  PLAYER_FIELD_BANK_SLOT_END           = UNIT_END + 0x01A7,
  PLAYER_FIELD_BANKBAG_SLOT_1          = UNIT_END + 0x01A8,
  PLAYER_FIELD_BANKBAG_SLOT_LAST       = UNIT_END + 0x01B2,
  PLAYER_FIELD_BANKBAG_SLOT_END        = UNIT_END + 0x01B3,
  PLAYER_FIELD_VENDORBUYBACK_SLOT_1    = UNIT_END + 0x01B4,
  PLAYER_FIELD_VENDORBUYBACK_SLOT_LAST = UNIT_END + 0x01CA,
  PLAYER_FIELD_VENDORBUYBACK_SLOT_END  = UNIT_END + 0x01CB,
  PLAYER_FIELD_KEYRING_SLOT_1          = UNIT_END + 0x01CC,
  PLAYER_FIELD_KEYRING_SLOT_LAST       = UNIT_END + 0x020A,
  PLAYER_FIELD_KEYRING_SLOT_END        = UNIT_END + 0x020B,

  PLAYER_FARSIGHT                      = UNIT_END + 0x020C,
  PLAYER_FARSIGHT_END                  = UNIT_END + 0x020E,
  PLAYER_FIELD_COMBO_TARGET            = UNIT_END + 0x020E,
  PLAYER_FIELD_COMBO_TARGET_END        = UNIT_END + 0x0210,
  PLAYER_XP                            = UNIT_END + 0x0210,
  PLAYER_NEXT_LEVEL_XP                 = UNIT_END + 0x0211,
  PLAYER_SKILL_INFO_1_1                = UNIT_END + 0x0212,
  PLAYER_CHARACTER_POINTS1             = UNIT_END + 0x0392,
  PLAYER_CHARACTER_POINTS2             = UNIT_END + 0x0393,
  PLAYER_TRACK_CREATURES               = UNIT_END + 0x0394,
  PLAYER_TRACK_RESOURCES               = UNIT_END + 0x0395,
  PLAYER_BLOCK_PERCENTAGE              = UNIT_END + 0x0396,
  PLAYER_DODGE_PERCENTAGE              = UNIT_END + 0x0397,
  PLAYER_PARRY_PERCENTAGE              = UNIT_END + 0x0398,
  PLAYER_CRIT_PERCENTAGE               = UNIT_END + 0x0399,
  PLAYER_RANGED_CRIT_PERCENTAGE        = UNIT_END + 0x039A,
  PLAYER_EXPLORED_ZONES_1              = UNIT_END + 0x039B,
  PLAYER_EXPLORED_ZONES_END            = UNIT_END + 0x03DA,
  PLAYER_REST_STATE_EXPERIENCE         = UNIT_END + 0x03DB,
  PLAYER_FIELD_COINAGE                 = UNIT_END + 0x03DC,
  PLAYER_FIELD_POSSTAT0                = UNIT_END + 0x03DD,
  PLAYER_FIELD_POSSTAT1                = UNIT_END + 0x03DE,
  PLAYER_FIELD_POSSTAT2                = UNIT_END + 0x03DF,
  PLAYER_FIELD_POSSTAT3                = UNIT_END + 0x03E0,
  PLAYER_FIELD_POSSTAT4                = UNIT_END + 0x03E1,
  PLAYER_FIELD_NEGSTAT0                = UNIT_END + 0x03E2,
  PLAYER_FIELD_NEGSTAT1                = UNIT_END + 0x03E3,
  PLAYER_FIELD_NEGSTAT2                = UNIT_END + 0x03E4,
  PLAYER_FIELD_NEGSTAT3                = UNIT_END + 0x03E5,
  PLAYER_FIELD_NEGSTAT4                = UNIT_END + 0x03E6,
  PLAYER_FIELD_RES_BUFF_MODS_POSITIVE = UNIT_END + 0x03E7,
  PLAYER_FIELD_RES_BUFF_MODS_POSITIVE_END = UNIT_END + 0x03ED,
  PLAYER_FIELD_RES_BUFF_MODS_NEGATIVE = UNIT_END + 0x03EE,
  PLAYER_FIELD_RES_BUFF_MODS_NEGATIVE_END = UNIT_END + 0x03F4,
  PLAYER_FIELD_MOD_DAMAGE_DONE_POS    = UNIT_END + 0x03F5,
  PLAYER_FIELD_MOD_DAMAGE_DONE_POS_END = UNIT_END + 0x03FB,
  PLAYER_FIELD_MOD_DAMAGE_DONE_NEG    = UNIT_END + 0x03FC,
  PLAYER_FIELD_MOD_DAMAGE_DONE_NEG_END = UNIT_END + 0x0402,
  PLAYER_FIELD_MOD_DAMAGE_DONE_PCT    = UNIT_END + 0x0403,
  PLAYER_FIELD_MOD_DAMAGE_DONE_PCT_END = UNIT_END + 0x0409,
  PLAYER_FIELD_BYTES                  = UNIT_END + 0x040A,
  PLAYER_AMMO_ID                      = UNIT_END + 0x040B,
  PLAYER_SELF_RES_SPELL               = UNIT_END + 0x040C,
  PLAYER_FIELD_PVP_MEDALS             = UNIT_END + 0x040D,
  PLAYER_FIELD_BUYBACK_PRICE_1        = UNIT_END + 0x040E,
  PLAYER_FIELD_BUYBACK_PRICE_LAST     = UNIT_END + 0x0419,
  PLAYER_FIELD_BUYBACK_TIMESTAMP_1    = UNIT_END + 0x041A,
  PLAYER_FIELD_BUYBACK_TIMESTAMP_LAST = UNIT_END + 0x0425,
  PLAYER_FIELD_SESSION_KILLS          = UNIT_END + 0x0426,
  PLAYER_FIELD_YESTERDAY_KILLS        = UNIT_END + 0x0427,
  PLAYER_FIELD_LAST_WEEK_KILLS        = UNIT_END + 0x0428,
  PLAYER_FIELD_THIS_WEEK_KILLS        = UNIT_END + 0x0429,
  PLAYER_FIELD_THIS_WEEK_CONTRIBUTION = UNIT_END + 0x042A,
  PLAYER_FIELD_LIFETIME_HONORABLE_KILLS = UNIT_END + 0x042B,
  PLAYER_FIELD_LIFETIME_DISHONORABLE_KILLS = UNIT_END + 0x042C,
  PLAYER_FIELD_YESTERDAY_CONTRIBUTION = UNIT_END + 0x042D,
  PLAYER_FIELD_LAST_WEEK_CONTRIBUTION = UNIT_END + 0x042E,
  PLAYER_FIELD_LAST_WEEK_RANK          = UNIT_END + 0x042F,
  PLAYER_FIELD_BYTES2                  = UNIT_END + 0x0430,
  PLAYER_FIELD_WATCHED_FACTION_INDEX  = UNIT_END + 0x0431,
  PLAYER_FIELD_COMBAT_RATING_1        = UNIT_END + 0x0432,
  PLAYER_FIELD_COMBAT_RATING_END      = UNIT_END + 0x0445,

  // Compatibility names retained for code paths that are disabled on Classic.
  PLAYER_UNSUPPORTED_FIELD             = UNIT_END + 0x0446,
  PLAYER_CHOSEN_TITLE                  = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FAKE_INEBRIATION              = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_CURRENCYTOKEN_SLOT_1   = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_KNOWN_TITLES            = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_KNOWN_TITLES1           = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_KNOWN_TITLES2           = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_KNOWN_CURRENCIES        = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_MOD_HEALING_DONE_POS   = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_MOD_HEALING_PCT         = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_MOD_SPELL_POWER_PCT     = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_MOD_TARGET_RESISTANCE   = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_ACTION_BAR_TOGGLES      = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_KILLS                   = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_TODAY_CONTRIBUTION      = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_HONOR_CURRENCY          = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_ARENA_CURRENCY          = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_MAX_LEVEL               = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_DAILY_QUESTS_1          = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_RUNE_REGEN_1                  = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_NO_REAGENT_COST_1             = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_GLYPH_SLOTS_1           = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_GLYPHS_1                = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_GLYPHS_ENABLED                = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_PET_SPELL_POWER               = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_EXPERTISE                     = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_OFFHAND_EXPERTISE             = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_OFFHAND_CRIT_PERCENTAGE       = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_SPELL_CRIT_PERCENTAGE1        = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_SHIELD_BLOCK                  = PLAYER_UNSUPPORTED_FIELD,
  PLAYER_FIELD_ARENA_TEAM_INFO_1_1    = PLAYER_UNSUPPORTED_FIELD,

  PLAYER_END                           = PLAYER_UNSUPPORTED_FIELD,
};

enum EGameObjectFields : std::uint16_t {
  GAMEOBJECT_FIELD_CREATED_BY = OBJECT_END + 0x0000,
  GAMEOBJECT_DISPLAYID        = OBJECT_END + 0x0002,
  GAMEOBJECT_FLAGS            = OBJECT_END + 0x0003,
  GAMEOBJECT_ROTATION         = OBJECT_END + 0x0004,
  GAMEOBJECT_PARENTROTATION   = GAMEOBJECT_ROTATION,
  GAMEOBJECT_STATE            = OBJECT_END + 0x0008,
  GAMEOBJECT_POS_X            = OBJECT_END + 0x0009,
  GAMEOBJECT_POS_Y            = OBJECT_END + 0x000A,
  GAMEOBJECT_POS_Z            = OBJECT_END + 0x000B,
  GAMEOBJECT_FACING           = OBJECT_END + 0x000C,
  GAMEOBJECT_DYN_FLAGS        = OBJECT_END + 0x000D,
  GAMEOBJECT_DYNAMIC          = GAMEOBJECT_DYN_FLAGS,
  GAMEOBJECT_FACTION          = OBJECT_END + 0x000E,
  GAMEOBJECT_TYPE_ID          = OBJECT_END + 0x000F,
  GAMEOBJECT_LEVEL            = OBJECT_END + 0x0010,
  GAMEOBJECT_ARTKIT           = OBJECT_END + 0x0011,
  GAMEOBJECT_ANIMPROGRESS     = OBJECT_END + 0x0012,
  GAMEOBJECT_BYTES_1          = GAMEOBJECT_STATE,
  GAMEOBJECT_PADDING          = OBJECT_END + 0x0013,
  GAMEOBJECT_END              = OBJECT_END + 0x0014,
};

enum EDynamicObjectFields : std::uint16_t {
  DYNAMICOBJECT_CASTER  = OBJECT_END + 0x0000,
  DYNAMICOBJECT_BYTES   = OBJECT_END + 0x0002,
  DYNAMICOBJECT_SPELLID = OBJECT_END + 0x0003,
  DYNAMICOBJECT_RADIUS  = OBJECT_END + 0x0004,
  DYNAMICOBJECT_POS_X   = OBJECT_END + 0x0005,
  DYNAMICOBJECT_POS_Y   = OBJECT_END + 0x0006,
  DYNAMICOBJECT_POS_Z   = OBJECT_END + 0x0007,
  DYNAMICOBJECT_FACING  = OBJECT_END + 0x0008,
  DYNAMICOBJECT_PADDING = OBJECT_END + 0x0009,
  DYNAMICOBJECT_END      = OBJECT_END + 0x000A,
  // Retained as a source-compatibility name. Classic does not serialize it.
  DYNAMICOBJECT_CASTTIME = DYNAMICOBJECT_END,
};

enum ECorpseFields : std::uint16_t {
  CORPSE_FIELD_OWNER         = OBJECT_END + 0x0000,
  CORPSE_FIELD_FACING        = OBJECT_END + 0x0002,
  CORPSE_FIELD_POS_X         = OBJECT_END + 0x0003,
  CORPSE_FIELD_POS_Y         = OBJECT_END + 0x0004,
  CORPSE_FIELD_POS_Z         = OBJECT_END + 0x0005,
  CORPSE_FIELD_DISPLAY_ID    = OBJECT_END + 0x0006,
  CORPSE_FIELD_ITEM          = OBJECT_END + 0x0007,
  CORPSE_FIELD_BYTES_1       = OBJECT_END + 0x001A,
  CORPSE_FIELD_BYTES_2       = OBJECT_END + 0x001B,
  CORPSE_FIELD_GUILD         = OBJECT_END + 0x001C,
  CORPSE_FIELD_FLAGS         = OBJECT_END + 0x001D,
  CORPSE_FIELD_DYNAMIC_FLAGS = OBJECT_END + 0x001E,
  CORPSE_FIELD_PAD           = OBJECT_END + 0x001F,
  // Classic has no corpse party field; retain the name only for old callers.
  CORPSE_FIELD_PARTY         = CORPSE_FIELD_OWNER,
  CORPSE_END                  = OBJECT_END + 0x0020,
};

inline constexpr std::uint8_t kMaxValuesMaskBlocks = 41;

inline constexpr std::uint16_t PLAYER_OTHER_END = PLAYER_END;

constexpr std::uint16_t FieldCountForPlayer(bool is_active_player) {
  return is_active_player ? PLAYER_END : PLAYER_OTHER_END;
}

constexpr std::uint16_t FieldCountFor(TypeID type) {
  switch (type) {
    case TypeID::kObject:        return OBJECT_END;
    case TypeID::kItem:          return ITEM_END;
    case TypeID::kContainer:     return CONTAINER_END;
    case TypeID::kUnit:          return UNIT_END;
    case TypeID::kPlayer:        return PLAYER_END;
    case TypeID::kGameObject:    return GAMEOBJECT_END;
    case TypeID::kDynamicObject: return DYNAMICOBJECT_END;
    case TypeID::kCorpse:        return CORPSE_END;
  }
  return OBJECT_END;
}

constexpr std::uint16_t FieldCountForOtherPlayer() {
  return PLAYER_OTHER_END;
}

template <typename FieldEnum, typename SectionEnum>
constexpr std::uint16_t DescriptorWordDistance(FieldEnum field,
                                               SectionEnum section_begin) {
  return static_cast<std::uint16_t>(static_cast<std::uint16_t>(field) -
                                    static_cast<std::uint16_t>(section_begin));
}

constexpr std::uint8_t BitmaskBlockCount(std::uint16_t field_count) {
  return static_cast<std::uint8_t>((field_count + 31) / 32);
}

static_assert(OBJECT_END == 6);
static_assert(ITEM_END == 48);
static_assert(CONTAINER_END == 122);
static_assert(UNIT_END == 188);
static_assert(PLAYER_END == 1282);
static_assert(GAMEOBJECT_END == 26);
static_assert(DYNAMICOBJECT_END == 16);
static_assert(CORPSE_END == 38);
static_assert(kMaxValuesMaskBlocks == BitmaskBlockCount(PLAYER_END));
static_assert(kNumClientObjectTypes == 8);

}
